version: '2'
services:
  kanboard:
    image: kanboard/kanboard:stable
    ports:
     - "80:80"
    volumes:
     - kanboard_data:/var/www/kanboard/data
     - kanboard_plugins:/var/www/kanboard/plugins
volumes:
  kanboard_data:
    driver: local
  kanboard_plugins:
    driver: local
